<?php

return array(
    'rec_reg_redir' => 'static_home',
    'logout_redirect' => 'static_home',
    'stu_reg_redir' => 'static_home',
    'comp_reg_redir' => 'static_home',
    'login_redir' => 'static_home',
    'proj_cre_redir' => 'static_home',
    'list_inv_redir' => 'mem_dashboard',
    'sector_names' => array(
        'Automobiles & Components',
        'Banks',
        'Capital Goods',
        'Commercial & Professional Services',
        'Consumer Durables & Apparel',
        'Diversified Financials',
        'Food & Drug Retailing',
        'Food Beverage & Tobacco',
        'Health Care Equipment & Services',
        'Hotels Restaurants & Leisure',
        'Household & Personal Products',
        'Pharmaceuticals & Biotechnology',
        'Real Estate',
        'Retailing',
        'Semiconductors & Semiconductor Equipment',
        'Software & Services',
        'Technology Hardware & Equipment',
        'Telecommunication Services',
        'Transportation',
        'Utilities',
        'Energy',
    ),
);
