@extends('layouts.static')
@section('content')
<div class="container form_block">
    <div class="row">
        <div class="col-xs-12">
            <h4>About Us</h4>
            <hr />
            <p>We’re a team of students and alums from <a title="Columbia" href="http://en.wikipedia.org/wiki/Columbia_University" target="_blank">Columbia</a>, <a title="Michigan" href="http://en.wikipedia.org/wiki/University_of_Michigan" target="_blank">Michigan </a>, <a title="Oxford" href="http://en.wikipedia.org/wiki/University_of_Oxford" target="_blank">Oxford </a>, <a title="Harvard" href="http://en.wikipedia.org/wiki/Harvard_University" target="_blank">Harvard </a>, <a title="University of Tokyo" href="http://en.wikipedia.org/wiki/University_of_Tokyo" target="_blank">University of Tokyo </a>, and <a title="IIT" href="http://en.wikipedia.org/wiki/Indian_Institutes_of_Technology" target="_blank">IIT</a>. We collectively have varied experience: from finance and consulting to microchip design and film production.</p>
            <p>Advisers: <a title="Tim Erway" href="http://www.linkedin.com/profile/view?id=17521732&amp;locale=en_US&amp;trk=tyah&amp;trkInfo=tas%3Atim%20erwa%2Cidx%3A1-1-1" target="_blank">Tim Erway</a>, <a title="Ian Tyree" href="http://www.linkedin.com/profile/view?id=42907092&amp;locale=en_US&amp;trk=tyah&amp;trkInfo=tas%3Aian%20tyree%2Cidx%3A1-1-1" target="_blank">Ian Tyree</a>, <a title="Ronald Philip" href="http://www.linkedin.com/profile/view?id=44048107&amp;locale=en_US&amp;trk=tyah&amp;trkInfo=tas%3Aronald%20philip%2Cidx%3A1-1-1" target="_blank">Ronald Philip</a>, <a title="Emma Furniss" href="http://www.linkedin.com/profile/view?id=11995806&amp;authType=NAME_SEARCH&amp;authToken=4SdV&amp;locale=en_US&amp;srchid=273513751388980338375&amp;srchindex=1&amp;srchtotal=8&amp;trk=vsrp_people_res_name&amp;trkInfo=VSRPsearchId%3A273513751388980338375%2CVSRPtargetId%3A11995806%2CVSRPcmpt%3Aprimary" target="_blank">Emma Furniss</a>, <a title="Takayugi Matsunaga" href="http://www.linkedin.com/profile/view?id=73940422&amp;authType=NAME_SEARCH&amp;authToken=xNZS&amp;locale=en_US&amp;srchid=273513751388980432096&amp;srchindex=1&amp;srchtotal=4&amp;trk=vsrp_people_res_name&amp;trkInfo=VSRPsearchId%3A273513751388980432096%2CVSRPtargetId%3A73940422%2CVSRPcmpt%3Aprimary" target="_blank">Takayugi Matsunaga</a></p>
            <p>Team: <a title="Aditya Sudhakar" href="http://www.linkedin.com/profile/view?id=27351375&amp;authType=NAME_SEARCH&amp;authToken=VOoK&amp;locale=en_US&amp;srchid=273513751388981939009&amp;srchindex=1&amp;srchtotal=2&amp;trk=vsrp_people_res_name&amp;trkInfo=VSRPsearchId%3A273513751388981939009%2CVSRPtargetId%3A27351375%2CVSRPcmpt%3Aprimary" target="_blank">Aditya Sudhakar</a>, <a title="Meghna Singhal" href="http://www.linkedin.com/profile/view?id=12709048&amp;locale=en_US&amp;trk=tyah&amp;trkInfo=tas%3Ameghna%20%2Cidx%3A1-2-2" target="_blank">Meghna Singhal</a>, <a title="Abhijit Sudhakar" href="http://jamicfilms.com" target="_blank">Abhijit Sudhakar</a>,&nbsp;<a title="Nimit Jain" href="http://www.linkedin.com/profile/view?id=106049131&amp;locale=en_US&amp;trk=tyah&amp;trkInfo=tas%3Animit%2Cidx%3A2-1-2" target="_blank">Nimit Jain</a></p>
        </div>
    </div>
</div>
@stop
